#pragma once 

namespace vega
{
	enum TOOOLSIDS
	{
		IDM_TOOLBAR_TOOL_SELECT = 200,
		IDM_TOOLBAR_TOOL_MOVE = 200,
		IDM_TOOLBAR_TOOL_ROTATE,
		IDM_TOOLBAR_TOOL_ROTATE_Y,
		IDM_TOOLBAR_TOOL_SCALE
	};
}